server:
  port: 8080

spring:
  application:
    name: rajbhog-backend

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: false

    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

  api-docs:
    path: /v3/api-docs

admin:
  email: ${ADMIN_EMAIL}
  name: Admin

rajbhog:
  store:
    latitude: 25.102699
    longitude: 84.123001
    delivery-radius-km: 10

razorpay:
  keyId: ${RAZORPAY_KEY}
  keySecret: ${RAZORPAY_SECRET}
